// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_MKWmHNZrhEta9fC_Aq8oB6le0UsZdbI',
    appId: '1:783900164571:web:bdf8702313314a4cc127fe',
    messagingSenderId: '783900164571',
    projectId: 'splitfree-c3af3',
    authDomain: 'splitfree-c3af3.firebaseapp.com',
    storageBucket: 'splitfree-c3af3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3EdTLWLoD91doImeB1UvKCz6wD2eCaW8',
    appId: '1:783900164571:android:c3f5969058faa687c127fe',
    messagingSenderId: '783900164571',
    projectId: 'splitfree-c3af3',
    storageBucket: 'splitfree-c3af3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnILieDsIFmewVwu7RL6A4S-9arXC5BT0',
    appId: '1:783900164571:ios:e25fab4ac9b58a9ec127fe',
    messagingSenderId: '783900164571',
    projectId: 'splitfree-c3af3',
    storageBucket: 'splitfree-c3af3.firebasestorage.app',
    iosBundleId: 'com.example.splitfree',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_MKWmHNZrhEta9fC_Aq8oB6le0UsZdbI',
    appId: '1:783900164571:web:bd589e5bcdd02a97c127fe',
    messagingSenderId: '783900164571',
    projectId: 'splitfree-c3af3',
    authDomain: 'splitfree-c3af3.firebaseapp.com',
    storageBucket: 'splitfree-c3af3.firebasestorage.app',
  );

}